# Server
server:
  port: 8080
  servlet:
    context-path: /community

# Spring
spring:

  # thymeleaf HTML模板
  thymeleaf:
    cache: false

  # DataSource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456

  # Mail
  mail:
    host: smtp.qq.com
    port: 465
    username: 562309285@qq.com
    password: rbqtuftpqteqbece
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  # Redis
  redis:
    database: 1
    host: localhost
    port: 6379

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: NowCoder-consumer-group
      enable-auto-commit: true    # 自动提交偏移量，读取消息的时候按偏移量读取的
      auto-commit-interval: 3000  # 自动提交频率

  # Elasticsearch
  data:
    elasticsearch:
      cluster-name: NowCoder
      cluster-nodes: 127.0.0.1:9200


  # TaskExecution
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 100
    scheduling:
      pool:
        size: 5

  # Quartz
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId=AUTO: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5





# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 映射文件存放位置
  type-aliases-package: edu.bjtu.community.entity     # 实体类的包名
  configuration:
    useGeneratedKeys: true                  # 自动生成主键：启用
    mapUnderscoreToCamelCase: true          # 匹配“字段的下划线”和“属性的驼峰命名”：启用


# Upload Path
community:
  path:
    domain: http://localhost:8080
    upload: F:/NowCoder/src/main/resources/upload

# logger
logging:
  level:
    edu:
      bjtu: debug
  file:
    name: F:/NowCoder/src/main/resources/log/community.log


# wk
wk:
  image:
    command: d:/work/wkhtmltopdf/bin/wkhtmltoimage
    storage: d:/work/data/wk-images

# qiniu
qiniu:
  key:
    access: 6RA-Uus95ZT_1znMrCMD8BpqfjT-K7OKmQTfKB48
    secret: kPNnLFz2_tzztKUVpSLm0lYngtuHWyIq5LzTmLI
  bucket:
    header:
      name: community_header
      url: http://pvghrij81.bkt.clouddn.com
    share:
      name: community_share
      url: http://pvghvvuzm.bkt.clouddn.com


# caffeine
caffeine:
  posts:
    max-size: 15
    expire-seconds: 180